/**
 * Downloads the woff2 files that public/fonts/ serves and regenerates
 * public/fonts/fonts.css.
 *
 *   npm run fetch:fonts
 *
 * The fonts are self-hosted so the page needs no DNS + TCP + TLS handshake to
 * fonts.googleapis.com and fonts.gstatic.com before any text can render — on a
 * high-latency mobile connection those handshakes cost more than the bytes do.
 *
 * Axis ranges below are narrowed to the weights src/index.css actually uses.
 * Widen them here if you introduce a heavier or lighter weight.
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const OUT_DIR = "public/fonts";

// Modern Chrome UA, so Google serves woff2 rather than legacy ttf.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

// The portfolio is English-only; skipping cyrillic/greek/vietnamese keeps the
// generated CSS small. Each subset is unicode-range gated, so latin-ext is only
// fetched by browsers that hit a character needing it.
const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);

const FAMILIES = [
  // Display face. Keeps the opsz axis (font-optical-sizing defaults to auto),
  // so headings render exactly as before. Weights used: 500/560/600/640/700.
  "Fraunces:ital,opsz,wght@0,9..144,400..700;1,9..144,400..700",
  // Body face. Weights used: 400/500/600/700.
  "Manrope:wght@400..700",
  // Labels and meta. Weights used: 500/600; no italic anywhere in the CSS.
  "JetBrains+Mono:wght@400..700",
];

const url = `https://fonts.googleapis.com/css2?${FAMILIES.map(
  (f) => `family=${f}`
).join("&")}&display=swap`;

const res = await fetch(url, { headers: { "User-Agent": UA } });
if (!res.ok) throw new Error(`Google Fonts returned ${res.status}`);
const css = await res.text();

const blocks = [
  ...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/g),
];
if (!blocks.length) throw new Error("Could not parse any @font-face blocks");

await mkdir(OUT_DIR, { recursive: true });

const out = [
  "/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.",
  "   Self-hosted so no external origin sits on the critical path. */",
  "",
];

let total = 0;
const seen = new Set();

for (const [, subset, block] of blocks) {
  if (!KEEP_SUBSETS.has(subset)) continue;

  const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
  const style = /font-style:\s*(\w+)/.exec(block)?.[1] ?? "normal";
  const weight = /font-weight:\s*([\d\s]+)/.exec(block)?.[1].trim();
  const srcUrl = /url\((https:\/\/[^)]+\.woff2)\)/.exec(block)?.[1];
  const unicodeRange = /unicode-range:\s*([^;]+);/.exec(block)?.[1].trim();
  if (!srcUrl) continue;

  const file = `${family.toLowerCase().replace(/\s+/g, "-")}-${style}-${subset}.woff2`;

  if (!seen.has(file)) {
    seen.add(file);
    const bin = await fetch(srcUrl, { headers: { "User-Agent": UA } });
    if (!bin.ok) throw new Error(`Font download failed: ${srcUrl}`);
    const buf = Buffer.from(await bin.arrayBuffer());
    await writeFile(path.join(OUT_DIR, file), buf);
    total += buf.length;
    console.log(`${file.padEnd(40)} ${(buf.length / 1024).toFixed(1).padStart(7)} KB`);
  }

  out.push(
    "@font-face {",
    `  font-family: "${family}";`,
    `  font-style: ${style};`,
    `  font-weight: ${weight};`,
    "  font-display: swap;",
    `  src: url("./${file}") format("woff2");`,
    ...(unicodeRange ? [`  unicode-range: ${unicodeRange};`] : []),
    "}",
    ""
  );
}

await writeFile(path.join(OUT_DIR, "fonts.css"), out.join("\n"), "utf8");
console.log(`\n${(total / 1024).toFixed(1)} KB across ${seen.size} files`);
